export const ADDRESS_SCHEMA = {
  MAX_LABEL: 50,
  RECIPIENT_NAME_MIN: 1,
  RECIPIENT_NAME_MAX: 120,
  PHONE_DIGITS_MIN: 8,
  PHONE_DIGITS_MAX: 30,
  ADDRESS_LINE_MIN: 5,
  ADDRESS_LINE_MAX: 255,
  POSTAL_CODE_LENGTH: 5
} as const;
